"""Deterministic evidence-item registry derived from EVALUATION.md.

The verifier LLM call returns category names and evidence-item labels as free
text, which can vary slightly in phrasing between turns (e.g. "UTR Number"
vs "UTR number"). The PDF generator needs stable item_id keys that don't
shift between runs. This module is the single source of truth for that
mapping, kept in code (not regenerated by the model) so the case file does
not silently lose fields due to LLM phrasing drift.

If EVALUATION.md is edited (categories/items added or renamed), this file
must be updated to match. There is a self-check at the bottom of this file
(see `verify_registry_matches_evaluation_md`) that agent.py can call at
startup to catch drift early instead of failing silently at PDF time.
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class EvidenceItem:
    item_id: str
    label: str


@dataclass(frozen=True)
class Category:
    category_id: str
    display_name: str
    required: tuple[EvidenceItem, ...]
    optional: tuple[EvidenceItem, ...] = field(default_factory=tuple)
    critical_flags: tuple[str, ...] = field(default_factory=tuple)
    # item_ids that are conditionally excluded from the denominator
    # (e.g. "Transaction history" for Remote Access Scam if no money was lost)
    conditional_item_ids: tuple[str, ...] = field(default_factory=tuple)


def _items(*pairs: tuple[str, str]) -> tuple[EvidenceItem, ...]:
    return tuple(EvidenceItem(item_id=i, label=l) for i, l in pairs)


CATEGORIES: dict[str, Category] = {
    "upi_fraud": Category(
        category_id="upi_fraud",
        display_name="UPI Fraud",
        required=_items(
            ("utr_number", "UTR Number"),
            ("transaction_id", "Transaction ID"),
            ("bank_account_involved", "Bank account involved"),
            ("transaction_datetime", "Date and time of transaction"),
            ("amount_transferred", "Amount transferred"),
            ("transaction_screenshot", "Screenshot of transaction"),
            ("beneficiary_account_details", "Beneficiary account details (if visible to the victim)"),
        ),
        optional=_items(
            ("fraudster_phone_number", "Fraudster phone number"),
            ("whatsapp_chats", "WhatsApp chats"),
            ("call_recordings", "Call recordings"),
            ("sms_alerts", "SMS alerts"),
        ),
        critical_flags=("No UTR Number", "No transaction screenshot", "No amount information"),
    ),
    "banking_fraud": Category(
        category_id="banking_fraud",
        display_name="Banking Fraud",
        required=_items(
            ("bank_name", "Bank name"),
            ("account_number_masked", "Account number (masked)"),
            ("transaction_ids", "Transaction IDs"),
            ("sms_alerts", "SMS alerts"),
            ("debit_notifications", "Debit notifications"),
            ("unauthorized_transaction_datetime", "Date and time of unauthorized transaction"),
        ),
        optional=_items(
            ("login_alerts", "Login alerts"),
            ("email_notifications", "Email notifications"),
            ("call_recordings", "Call recordings"),
        ),
        critical_flags=(
            "No transaction proof (no Transaction IDs, SMS alerts, or Debit notifications)",
            "No bank details (no Bank name or Account number)",
            "No transaction timeline (no Date and time)",
        ),
    ),
    "sim_swap_fraud": Category(
        category_id="sim_swap_fraud",
        display_name="SIM Swap Fraud",
        required=_items(
            ("mobile_number_affected", "Mobile number affected"),
            ("loss_of_network_screenshot", "Loss-of-network screenshot"),
            ("telecom_sms", "SMS from telecom operator"),
            ("service_stopped_datetime", "Date and time service stopped"),
        ),
        optional=_items(
            ("telecom_complaint_number", "Telecom complaint number"),
            ("call_records", "Call records"),
            ("device_screenshots", "Device screenshots"),
        ),
        critical_flags=("No telecom messages", "No affected number", "No timeline"),
    ),
    "whatsapp_hijack": Category(
        category_id="whatsapp_hijack",
        display_name="WhatsApp Account Hijack",
        required=_items(
            ("affected_phone_number", "Affected phone number"),
            ("whatsapp_login_alert", "WhatsApp login alert"),
            ("logout_screenshot", "Screenshot of logout"),
            ("unauthorized_messages_sent", "Unauthorized messages sent from the account"),
        ),
        optional=_items(
            ("linked_device_screenshots", "Linked-device screenshots"),
            ("fraudster_messages_received", "Fraudster messages received by the victim"),
        ),
        critical_flags=(
            "No screenshots (neither login alert nor logout screenshot)",
            "No account identifier (no affected phone number)",
        ),
    ),
    "social_media_takeover": Category(
        category_id="social_media_takeover",
        display_name="Social Media Account Takeover",
        required=_items(
            ("platform_name", "Platform name"),
            ("username_or_profile_url", "Username / profile URL"),
            ("login_alert_emails", "Login alert emails"),
            ("recovery_emails", "Recovery emails"),
            ("unauthorized_posts_messages", "Unauthorized posts/messages"),
        ),
        optional=_items(
            ("device_history", "Device history"),
            ("session_logs", "Session logs"),
        ),
        critical_flags=(
            "No profile information (no Platform name or Username/profile URL)",
            "No login evidence (no Login alert emails or Recovery emails)",
        ),
    ),
    "phishing_scam": Category(
        category_id="phishing_scam",
        display_name="Phishing Scam",
        required=_items(
            ("url_clicked", "URL clicked"),
            ("website_screenshot", "Screenshot of website"),
            ("phishing_message", "Phishing email/message"),
            ("interaction_datetime", "Date and time interaction occurred"),
        ),
        optional=_items(
            ("browser_history", "Browser history"),
            ("email_headers", "Email headers"),
        ),
        critical_flags=("No URL", "No phishing message"),
    ),
    "qr_code_scam": Category(
        category_id="qr_code_scam",
        display_name="QR Code Scam",
        required=_items(
            ("qr_code_image", "QR code image"),
            ("payment_screenshot", "Payment screenshot"),
            ("utr_number", "UTR number"),
            ("transaction_amount", "Transaction amount"),
        ),
        optional=_items(
            ("chat_history", "Chat history"),
            ("merchant_information", "Merchant information"),
        ),
        critical_flags=(
            "No QR code screenshot",
            "No transaction evidence (no Payment screenshot and no UTR number)",
        ),
    ),
    "remote_access_scam": Category(
        category_id="remote_access_scam",
        display_name="Remote Access Scam",
        required=_items(
            ("application_installed", "Application installed"),
            ("app_name", "App name"),
            ("installation_time", "Installation time"),
            ("permissions_screenshots", "Screenshots of permissions granted"),
            ("transaction_history", "Transaction history (only required if money loss occurred)"),
        ),
        optional=_items(
            ("apk_file", "APK file"),
            ("call_recordings", "Call recordings"),
        ),
        critical_flags=("Unknown app (no App name)", "No device evidence (no Screenshots of permissions granted)"),
        conditional_item_ids=("transaction_history",),
    ),
    "mobile_hacking_malware": Category(
        category_id="mobile_hacking_malware",
        display_name="Mobile Phone Hacking / Malware",
        required=_items(
            ("device_type", "Device type"),
            ("os_version", "OS version"),
            ("suspicious_app_name", "Suspicious application name"),
            ("apk_file", "APK file (if available)"),
            ("suspicious_behavior_screenshots", "Screenshots of suspicious behavior"),
        ),
        optional=_items(
            ("antivirus_reports", "Antivirus reports"),
            ("accessibility_permissions", "Accessibility permissions"),
            ("device_logs", "Device logs"),
        ),
        critical_flags=("Unknown suspicious app (no Suspicious application name)", "No screenshots"),
    ),
    "investment_scam": Category(
        category_id="investment_scam",
        display_name="Investment Scam",
        required=_items(
            ("platform_name", "Platform name"),
            ("website_url", "Website URL"),
            ("wallet_account_details", "Wallet/account details"),
            ("transaction_records", "Transaction records"),
            ("deposit_screenshots", "Deposit screenshots"),
        ),
        optional=_items(
            ("telegram_chat_history", "Telegram/chat group history"),
            ("account_manager_details", "Account manager details"),
        ),
        critical_flags=(
            "No transaction proof (no Transaction records and no Deposit screenshots)",
            "No platform information (no Platform name or Website URL)",
        ),
    ),
    "job_scam": Category(
        category_id="job_scam",
        display_name="Job Scam",
        required=_items(
            ("job_posting", "Job posting"),
            ("company_name", "Company name"),
            ("communication_screenshots", "Communication screenshots"),
            ("payment_request_evidence", "Payment request evidence"),
            ("email_addresses_used", "Email addresses used"),
        ),
        optional=_items(
            ("offer_letter", "Offer letter"),
            ("contract", "Contract"),
        ),
        critical_flags=(
            "No communication evidence (no Communication screenshots)",
            "No payment proof (no Payment request evidence) — only if financial loss reported",
        ),
        conditional_item_ids=("payment_request_evidence",),
    ),
    "ecommerce_fraud": Category(
        category_id="ecommerce_fraud",
        display_name="E-Commerce / Shopping Fraud",
        required=_items(
            ("order_id", "Order ID"),
            ("seller_profile", "Seller profile"),
            ("payment_receipt", "Payment receipt"),
            ("product_listing", "Product listing"),
        ),
        optional=_items(
            ("tracking_information", "Tracking information"),
            ("seller_chat_conversations", "Chat conversations with seller"),
        ),
        critical_flags=("No order details (no Order ID)", "No payment proof (no Payment receipt)"),
    ),
    "sextortion": Category(
        category_id="sextortion",
        display_name="Sextortion",
        required=_items(
            ("threat_messages", "Threat messages"),
            ("attacker_usernames_handles", "Usernames/handles of attacker"),
            ("payment_demands", "Payment demands"),
            ("attacker_wallet_account_details", "Wallet/account details used by attacker (only if payment demanded)"),
        ),
        optional=_items(
            ("images_videos_shared", "Images/videos shared (confirmation of existence only, never require upload)"),
            ("attacker_social_profiles", "Social media profiles of attacker"),
        ),
        critical_flags=("No threat evidence (no Threat messages)", "No account identifiers (no Usernames/handles)"),
        conditional_item_ids=("attacker_wallet_account_details",),
    ),
    "cyberbullying_harassment": Category(
        category_id="cyberbullying_harassment",
        display_name="Cyber Bullying / Harassment",
        required=_items(
            ("messages_posts", "Messages/posts"),
            ("content_urls", "URLs (where the content is hosted)"),
            ("offender_usernames", "Usernames of offender(s)"),
            ("dates_timestamps", "Dates and timestamps"),
        ),
        optional=_items(
            ("witness_statements", "Witness statements"),
        ),
        critical_flags=("No screenshots (no Messages/posts)", "No offender identifier (no Usernames)"),
    ),
    "identity_theft": Category(
        category_id="identity_theft",
        display_name="Identity Theft",
        required=_items(
            ("misused_document_details", "Misused document details (e.g. Aadhaar, PAN, passport)"),
            ("fraudulent_account_transaction_details", "Fraudulent account/transaction details created using the identity"),
            ("misuse_notices", "Emails/messages/notices showing the misuse"),
        ),
        optional=_items(
            ("credit_reports", "Credit reports"),
            ("prior_complaint_reference_numbers", "Prior complaint reference numbers"),
        ),
        critical_flags=(
            "No proof of misuse (no Fraudulent account/transaction details and no Emails/messages showing misuse)",
            "No affected identity document specified",
        ),
    ),
    "uncategorized_other": Category(
        category_id="uncategorized_other",
        display_name="Uncategorized / Other Cybercrime",
        required=_items(
            ("incident_description", "Clear description of what happened, including platform/channel involved"),
            ("incident_datetime", "Date and time of incident"),
            ("supporting_files", "Any screenshots, messages, or files related to the incident"),
            ("other_party_identifier", "Identifier of the other party (username, phone number, account, or URL), if known"),
        ),
        optional=_items(
            ("witness_statements", "Witness statements"),
            ("financial_records", "Any financial records, if money was involved"),
        ),
        critical_flags=("No incident description", "No timeline", "No supporting evidence of any kind"),
    ),
}

# Map common label variants the verifier LLM might emit back to category_id.
# Used as a fallback if the LLM doesn't return our exact category_id strings.
DISPLAY_NAME_TO_ID = {cat.display_name.lower(): cid for cid, cat in CATEGORIES.items()}


def resolve_category_id(name: str) -> str | None:
    """Best-effort match of a free-text category name to a registry category_id."""
    if not name:
        return None
    key = name.strip().lower()
    if key in CATEGORIES:
        return key
    if key in DISPLAY_NAME_TO_ID:
        return DISPLAY_NAME_TO_ID[key]
    # loose contains-match fallback (e.g. "UPI fraud case" -> upi_fraud)
    for display, cid in DISPLAY_NAME_TO_ID.items():
        if display in key or key in display:
            return cid
    return None


def resolve_item_id(category_id: str, label: str) -> str | None:
    """Best-effort match of a free-text evidence label to a registry item_id."""
    category = CATEGORIES.get(category_id)
    if not category or not label:
        return None
    key = label.strip().lower()
    for item in (*category.required, *category.optional):
        if item.label.lower() == key:
            return item.item_id
        if item.label.lower().split(" (")[0] in key or key in item.label.lower():
            return item.item_id
    return None
