"""First-turn triage: detect financial loss fast, without waiting on a full
interview, so the user gets the golden-hour advisory immediately.

Design choices:
- Regex/keyword pass first (fast, deterministic, free). Only falls back to
  an LLM call when the signal is genuinely ambiguous, per design decision.
- The urgent-action message itself is a FIXED TEMPLATE, not generated by
  the model. This is deliberate: the advice (call 1930, file at
  cybercrime.gov.in, contact your bank) is factual and time-sensitive, and
  we do not want phrasing drift to turn accurate urgency into manufactured
  pressure over many model calls. The model is free to add empathetic
  framing in its own next turn, but the actionable core stays fixed.
"""

from __future__ import annotations

import re
from typing import Literal

FinancialSignal = Literal["yes", "no", "ambiguous"]

_POSITIVE_PATTERNS = [
    r"\b(debited|deducted|withdrawn|transferred|sent)\b.*\b(money|amount|rs\.?|inr|₹|rupees?)\b",
    r"\b(rs\.?|inr|₹)\s?\d",
    r"\blost\b.{0,20}\b(money|rupees|amount|₹|rs\.?|inr|lakh|crore)\b",
    r"\b(upi|paytm|gpay|phonepe|neft|imps|rtgs)\b.{0,30}\b(fraud|scam|unauthorized|hack)\b",
    r"\bbank account\b.{0,30}\b(hack|fraud|unauthorized|debit)\b",
    r"\b(otp|cvv|pin)\b.{0,30}\b(shared|gave|told|entered)\b",
    r"\binvestment\b.{0,30}\b(scam|fraud|lost)\b",
    r"\bcredit card\b.{0,30}\b(fraud|unauthorized|charge)\b",
]

_NEGATIVE_PATTERNS = [
    r"\bno money\b",
    r"\bdidn'?t lose (any )?money\b",
    r"\bno financial loss\b",
    r"\bharassment\b",
    r"\bbullying\b",
    r"\bblackmail\b",
    r"\bjust (asking|curious|checking)\b",
]


def detect_financial_loss_regex(text: str) -> FinancialSignal:
    lowered = text.lower()
    positive = any(re.search(p, lowered) for p in _POSITIVE_PATTERNS)
    negative = any(re.search(p, lowered) for p in _NEGATIVE_PATTERNS)

    if positive and not negative:
        return "yes"
    if negative and not positive:
        return "no"
    if not positive and not negative:
        # No strong signal either way — short/vague first messages are common
        # ("someone hacked my account") and shouldn't trigger an LLM call.
        return "no"
    return "ambiguous"


def detect_financial_loss_llm(text: str, call_azure_openai) -> bool:
    """Cheap, narrow classification call used only when the regex pass is
    ambiguous (positive and negative signals both present)."""
    raw = call_azure_openai(
        [
            {
                "role": "system",
                "content": (
                    "Classify whether the user's message describes an INCIDENT "
                    "WITH ACTUAL OR ATTEMPTED FINANCIAL LOSS (money debited, "
                    "transferred, or at risk of being transferred right now). "
                    "Respond with exactly one word: yes or no."
                ),
            },
            {"role": "user", "content": text},
        ],
        temperature=0,
    )
    return raw.strip().lower().startswith("y")


URGENT_FINANCIAL_NOTICE = """\
**If money has been taken or is at risk, act now — these steps work best in the first 30–60 minutes ("the golden hour"):**

1. **Call 1930** (National Cyber Crime Helpline) right now. This can trigger an immediate hold on the funds before they move further.
2. **File at https://cybercrime.gov.in/Webform/Accept.aspx** — this is the official portal that flags the transaction for a freeze across banks.
3. **Call your bank's official fraud/dispute helpline** (use the number on your card or bank app — not a number anyone sent you) and ask them to block the transaction and freeze the receiving account.

Do all three if you can — they work together, not as alternatives. I'll help you with the report and the details while you do this.
"""


def build_triage_notice(financial_loss: bool) -> str | None:
    if financial_loss:
        return URGENT_FINANCIAL_NOTICE
    return None
